unit uCodeGen;

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils, ubackend, dateutils, ucode, usymtab, umessages;

type

  { TCodeGenerator }

  TCodeGenerator = class(TBackEnd)
    public
      procedure Process(AICode: IIntermediateCode; ASymtab: ISymtab); override;
  end;

implementation


{ TCodeGenerator }

// Process the intermediate code and the symbol table generated by the
// parser.  To be implemented by a compiler or an interpreter subclass.
procedure TCodeGenerator.Process(AICode : IIntermediateCode; ASymtab : ISymtab);
var
  StartTime: QWord;
  Elapsed: LongWord;
  InstructionCount: integer;
begin
  StartTime := getTickCount64;

  InstructionCount := 0;

  Elapsed := getTickCount64 - startTime;

  SendMessage(TMessage.Create(mtCompilerSummary,
    TCompilerSummaryMsg.Create(InstructionCount, Elapsed)));

end;




end.

