unit uExecutor;

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils, ubackend, dateutils, ucode, usymtab, umessages;

type
  TExecutor = class(TBackEnd)
    public
      procedure Process(AICode: IIntermediateCode; ASymtab: ISymtab); override;
  end;

implementation


{ TCodeGenerator }

// Process the intermediate code and the symbol table generated by the
// parser to execute the source program.
procedure TExecutor.Process(AICode : IIntermediateCode; ASymtab : ISymtab);
var
  StartTime: QWord;
  Elapsed: LongWord;
  ExecutionCount: integer;
  RuntimeErrors: integer;
begin
  StartTime := getTickCount64;

  ExecutionCount := 0;
  RuntimeErrors := 0;

  Elapsed := getTickCount64 - startTime;

  SendMessage(TMessage.Create(mtInterpreterSummary,
    TInterpreterSummaryMsg.Create(ExecutionCount, RuntimeErrors, Elapsed)));

end;



end.

