unit uExecutor;

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils, ubackend, dateutils, ucode, usymtab, umessages;

type

  { TExecutor }

  TExecutor = class(TBackEnd)
    public
      procedure Process(AICode: IIntermediateCode;
        ASymtabStack: ISymtabStack); override;
  end;

implementation


{ TCodeGenerator }

// Process the intermediate code and the symbol table generated by the
// parser to execute the source program.
procedure TExecutor.Process(AICode: IIntermediateCode;
  ASymtabStack: ISymtabStack);
var
  StartTime: TDateTime;
  ElapsedTime: Double;
  ExecutionCount: integer;
  RuntimeErrors: integer;
begin
  StartTime := TimeOf(Now);

  ExecutionCount := 0;
  RuntimeErrors := 0;

  ElapsedTime := SecondSpan(StartTime, TimeOf(Now));

  SendMessage(TMessage.Create(mtInterpreterSummary,
    TInterpreterSummaryMsg.Create(ExecutionCount, RuntimeErrors, ElapsedTime)));

end;



end.

