unit uCodeGen;

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils, ubackend, dateutils, ucode, usymtab, umessages;

type

  { TCodeGenerator }

  TCodeGenerator = class(TBackEnd)
    public
      procedure Process(AICode: IIntermediateCode; ASymtab: ISymtab); override;
  end;

implementation


{ TCodeGenerator }

// Process the intermediate code and the symbol table generated by the
// parser.  To be implemented by a compiler or an interpreter subclass.
procedure TCodeGenerator.Process(AICode : IIntermediateCode; ASymtab : ISymtab);
var
  StartTime, EndTime: TDateTime;
  ElapsedTime: real;
  InstructionCount: integer;
begin
  StartTime := TimeOf(Now);

  InstructionCount := 0;

  EndTime := TimeOf(Now);
  ElapsedTime := SecondSpan(StartTime,EndTime);

  SendMessage(TMessage.Create(mtCompilerSummary,
    TCompilerSummaryMsg.Create(InstructionCount, ElapsedTime)));

end;




end.

